# .github/workflows/pr.yml
name: PR Pipeline

on:
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: npm ci

      - name: Install browsers
        run: npx playwright install

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Lint (Biome)
        run: |
          npx @biomejs/biome check . --write
          git diff --exit-code

      # - name: Lint (Biome)
      #  run: npx @biomejs/biome check .

      - name: Run Playwright tests
        run: npx playwright test